- name : creating ec2 instances and r53 records
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0303a0e47aba592a6
    domain_name: daws-86.shop

  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: "t3.micro"
        image_id: "{{ ami_id }}"
        security_group: "{{ sg_id }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output
        
